# Generated by Django 4.1 on 2024-09-30 16:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aukce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(default='', max_length=100)),
                ('popis', models.TextField(default='')),
                ('minimalni_prihoz', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('castka_kup_ted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('propagace', models.BooleanField(default=False)),
                ('lokalita', models.CharField(default='', max_length=100)),
                ('datum_zacatku', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_ukonceni', models.DateTimeField(default=django.utils.timezone.now)),
                ('pocet_zobrazeni', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('muze_vytvorit_kategorii', 'Může vytvářet kategorie')],
            },
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('mesto', models.CharField(blank=True, max_length=100)),
                ('adresa', models.CharField(blank=True, max_length=100)),
                ('stav_uctu', models.CharField(choices=[('ACTIVE', 'Aktivní'), ('INACTIVE', 'Neaktivní'), ('BLOCKED', 'Blokovaný')], default='ACTIVE', max_length=10)),
                ('vznik_uctu', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='uzivatel', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='uzivatel', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('datum_prihozu', models.DateTimeField(auto_now_add=True)),
                ('aukce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.aukce')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aukce',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.kategorie'),
        ),
        migrations.AddField(
            model_name='aukce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
