# Generated by Django 4.1 on 2024-09-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aukce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(default='', max_length=100)),
                ('popis', models.TextField(default='')),
                ('minimalni_prihoz', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('castka_kup_ted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('propagace', models.BooleanField(default=False)),
                ('lokalita', models.CharField(default='', max_length=100)),
                ('datum_zacatku', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_ukonceni', models.DateTimeField(default=django.utils.timezone.now)),
                ('pocet_zobrazeni', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('datum_prihozu', models.DateTimeField(auto_now_add=True)),
                ('aukce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.aukce')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aukce',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.kategorie'),
        ),
        migrations.AddField(
            model_name='aukce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
