# Generated by Django 4.1 on 2024-09-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'permissions': [('muze_vytvorit_kategorii', 'Může vytvářet kategorie')]},
        ),
    ]
