# Generated by Django 4.1 on 2024-09-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_aukce_vitez'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukce',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktivní'), ('ENDED', 'Ukončená'), ('BOUGHT', 'Zakoupená')], default='ACTIVE', max_length=10),
        ),
    ]
