# Generated by Django 4.1 on 2024-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status_uctu',
        ),
    ]
