# Generated by Django 4.1 on 2024-10-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_aukce_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress',
            new_name='address',
        ),
    ]
