# Generated by Django 4.1 on 2024-10-01 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0005_rename_adress_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_aukce', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rating_prodejce', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar_prodejce', models.TextField(blank=True, null=True)),
                ('rating_kupujiciho', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar_kupujiciho', models.TextField(blank=True, null=True)),
                ('aukce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoceni', to='auction.aukce')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
