# Generated by Django 4.1 on 2024-10-03 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0006_hodnoceni'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukce',
            name='sledujici',
            field=models.ManyToManyField(blank=True, related_name='sledovane_aukce', to=settings.AUTH_USER_MODEL),
        ),
    ]
