# Generated by Django 4.1 on 2024-10-03 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_aukce_sledujici'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
