# Generated by Django 4.1 on 2024-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_kategorie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodnoceni',
            name='rating_kupujiciho',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='hodnoceni',
            name='rating_prodejce',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
