# Generated by Django 4.1 on 2024-10-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_hodnoceni_rating_kupujiciho_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hodnoceni',
            old_name='komentar_kupujiciho',
            new_name='komentar_k_aukci',
        ),
        migrations.RemoveField(
            model_name='hodnoceni',
            name='komentar_prodejce',
        ),
        migrations.RemoveField(
            model_name='hodnoceni',
            name='rating_kupujiciho',
        ),
    ]
