# Generated by Django 4.1 on 2024-10-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukce',
            name='aktualni_castka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
