# Generated by Django 4.1 on 2024-10-14 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0015_aukce_aktualni_castka'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukce',
            name='nejvyssi_prihoz_uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nejvyssi_prihoz_aukce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aukce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vytvorene_aukce', to=settings.AUTH_USER_MODEL),
        ),
    ]
