# Generated by Django 4.1 on 2024-10-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_aukce_nejvyssi_prihoz_uzivatel_alter_aukce_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukce',
            name='waiting_for_premium_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
