# Generated by Django 4.1 on 2024-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_aukce_waiting_for_premium_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aukce',
            name='waiting_for_premium_confirmation',
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_for_premium_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
